import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {PrimeReactProvider} from "primereact/api";
import "./globals.css";
import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';
import ContentLayout from "@/components/ContentLayout/ContentLayout";
import SideBar from "@/components/Menu/SideBar/SideBar";
import {SMenuProvider} from "@/context/menuNavigationContext";
import {FormProvider} from "@/context/formContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SoftSess",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <PrimeReactProvider value={{ unstyled: false }}>
            <FormProvider>
              <SMenuProvider>
                <SideBar />
                <ContentLayout>
                  {children}
                </ContentLayout>
              </SMenuProvider>
            </FormProvider>
          </PrimeReactProvider>
        </main>
      </body>
    </html>
  );
}
