import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {PrimeReactProvider} from "primereact/api";
import "./globals.css";
import 'primereact/resources/primereact.css';
import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';
import ContentLayout from "@/components/ContentLayout/ContentLayout";
import SideBar from "@/components/Menu/SideBar/SideBar";
import {SMenuProvider} from "@/context/menuContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <PrimeReactProvider value={{ unstyled: false }}>
            <SMenuProvider>
              <SideBar />
              <ContentLayout>
                {children}
              </ContentLayout>
            </SMenuProvider>
          </PrimeReactProvider>
        </main>
      </body>
    </html>
  );
}
