import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {PrimeReactProvider} from "primereact/api";
import "./globals.css";
import 'primereact/resources/primereact.css';
import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <PrimeReactProvider value={{ unstyled: false }}>{children}</PrimeReactProvider>
        </main>
      </body>
    </html>
  );
}
